fixtures:
    symlinks:
      rancher: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.3.2
      docker:
        repo: https://github.com/garethr/garethr-docker.git
      epel:
        repo: https://github.com/stahnma/puppet-module-epel
    forge_modules:
